### ISSUE TITLE
Copied my code

### ISSUE THREAD

**Issue by daedalus** [tm31420/Break-Secp256K1-Task-23122.421#1]
Hi,

I'm seeing that you verbatim copied a portion of my code, that's fine but I see that I has been striped of it's attribution. Please kindly add the missing header into the file crackrsz.py which is based in https://github.com/daedalus/BreakingECDSAwithLLL/blob/master/crack_weak_ECDSA_nonces_with_LLL.py

**Comment by tm31420** [comment]
Hi Dario,
Will do. I apologize.

**Comment by daedalus** [comment]
I really appreciate that, thanks to you.
